FROM node:20-alpine
WORKDIR /app

ENV PNPM_STORE_DIR=/app/.pnpm-store
# Enable corepack (Node's package manager manager)
RUN corepack enable

# Use corepack to prepare pnpm
RUN corepack prepare pnpm@latest --activate

# Copy pnpm lockfile and package.json
COPY package.json pnpm-lock.yaml ./

# Install dependencies using pnpm
RUN pnpm install 

# Expose the default Next.js dev port
EXPOSE 3000

# Use 'pnpm dev' to start the server
CMD ["pnpm", "dev"]